apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: website
  namespace: argocd
spec:
  destination:
    namespace: website
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitea.cluster.stevenchen.one/steven/website-argo.git
    targetRevision: main
    path: apps/website
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    automated:
      selfHeal: true
      prune: true
