apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
  namespace: website
spec:
  selector:
    matchLabels:
      app: personal-website
  replicas: 2
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
        - name: nginx
          image: gitea.cluster.stevenchen.one/steven/personal-website:d0958112acc90a0f031fa5655cf98b15c070aa34
          ports:
            - containerPort: 80
